# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_pb2 as message__pb2


class MessageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServeMapper = channel.unary_unary(
                '/message.Message/ServeMapper',
                request_serializer=message__pb2.RequestMapper.SerializeToString,
                response_deserializer=message__pb2.ResponseMapper.FromString,
                )
        self.ServeReducer = channel.unary_unary(
                '/message.Message/ServeReducer',
                request_serializer=message__pb2.RequestReducer.SerializeToString,
                response_deserializer=message__pb2.ResponseReducer.FromString,
                )


class MessageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ServeMapper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServeReducer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ServeMapper': grpc.unary_unary_rpc_method_handler(
                    servicer.ServeMapper,
                    request_deserializer=message__pb2.RequestMapper.FromString,
                    response_serializer=message__pb2.ResponseMapper.SerializeToString,
            ),
            'ServeReducer': grpc.unary_unary_rpc_method_handler(
                    servicer.ServeReducer,
                    request_deserializer=message__pb2.RequestReducer.FromString,
                    response_serializer=message__pb2.ResponseReducer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.Message', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Message(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ServeMapper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.Message/ServeMapper',
            message__pb2.RequestMapper.SerializeToString,
            message__pb2.ResponseMapper.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServeReducer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.Message/ServeReducer',
            message__pb2.RequestReducer.SerializeToString,
            message__pb2.ResponseReducer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
